### ISSUE TITLE
Create first iteration for conference list page with data sourced from a markdown files in the repository

### ISSUE THREAD

**Issue by programmiri** [conference-buddy/conference-buddy-web-app#2]
# Description

- User need to see a list of conferences where they can connect with potential Conference Buddys. 

## First iteration
- This list should show name, date, location of the conference. (later also tags and cta, ignore them on mockup)
- data should live in this repository (markdown) and sourced from here

## Mockup
<img width="989" alt="conferencelist-iteration-001" src="https://user-images.githubusercontent.com/943800/144715401-e2282d29-328d-4064-9013-a7369bfa2f6e.png">

**Comment by programmiri** [comment]
## todos

### definitely
- [ ]  check use of `Layout` component (test ability in mind)
- [ ]  add styles for bigger screens (optimized for mobile first currently)
- [ ]  test accessibility manually
- [ ] add tests for existing small components (snapshot?)
- [ ] graphql testing...??

### maybe later (copy&paste this to new/next issue)
- [ ] clean up typescript chaos and add proper typing / interfaces (maybe move that a bit until data structure is more clear?)
- [ ]  check for automated accessibility testing

**Comment by coderbyheart** [comment]
The mapping between GraphQL results and TypeScript can be solved by defining a type for the properties in the pages. After all they need to follow a certain structure to be rendered properly. Eventually the proper structure of the pages could be verified using a JSON schema.

It could also help to separate[ the code that loads the data](https://github.com/conference-buddy/conference-buddy-web-app/blob/2875f1d6a54824ec248f01d529afa1885e0cf183/src/pages/conference-list.tsx#L8-L33) from [the code that displays it](https://github.com/conference-buddy/conference-buddy-web-app/blob/2875f1d6a54824ec248f01d529afa1885e0cf183/src/pages/conference-list.tsx#L41-L47), after all the TSX that renders the data doesn't need to care where the data comes from, and could be moved to a separate file.

**Comment by programmiri** [comment]
Hi! Thanks for the input! 

I need to take a bit time to checkout how TS is used best in React and in combination with GraphQL (also: dive a bit into GraphQL 😅) to figure out how to use TS best and also how to separate files and probably also update the structure of the directory. It's a lot of new things right now (or: forgotten things), phew! 

Really appreciate your input on that 🙏  so, please bring it on! I also have given you access to the priv repository "product development" where I want to write these kind of things down to keep track on them a bit, you can also use that if you want.
